spring.application.name=audit

spring.datasource.url=jdbc:postgresql://localhost:5432/curbcutting
spring.datasource.username=postgres
spring.datasource.password=devpassword

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false